<?php

namespace AppBundle\Repository;

/**
 * TesztRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TesztRepository extends \Doctrine\ORM\EntityRepository
{
}
