Gradient_index:
    path:     /
    defaults: { _controller: "AppBundle:Teszt:index" }
    methods:  GET

Gradient_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Teszt:show" }
    methods:  GET

Gradient_new:
    path:     /new
    defaults: { _controller: "AppBundle:Teszt:new" }
    methods:  [GET, POST]

Gradient_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Teszt:edit" }
    methods:  [GET, POST]

Gradient_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Teszt:delete" }
    methods:  DELETE
