AppBundle\Entity\Teszt:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TesztRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        teszt:
            type: string
            length: 255
    lifecycleCallbacks: {  }
